### ISSUE TITLE
Failed to install from git

### ISSUE THREAD

**Issue by norohind** [WhiteApfel/pyYaOTP#1]
Installation using `python pip install git+https://github.com/WhiteApfel/pyYaOTP.git` fails.
I tried on 3.10.9 x64 on Windows
```
python -m pip install git+https://github.com/WhiteApfel/pyYaOTP.git
Collecting git+https://github.com/WhiteApfel/pyYaOTP.git
  Cloning https://github.com/WhiteApfel/pyYaOTP.git to c:\users\computer\appdata\local\temp\pip-req-build-fahc_t_o
  Running command git clone --filter=blob:none --quiet https://github.com/WhiteApfel/pyYaOTP.git 'C:\Users\Computer\AppData\Local\Temp\pip-req-build-fahc_t_o'
  Resolved https://github.com/WhiteApfel/pyYaOTP.git to commit 262b65463ee8ebf8dc5516b04fc2d78b5a09ae8c
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Computer\AppData\Local\Temp\pip-req-build-fahc_t_o\setup.py", line 19, in <module>
          version=environ.get("TAG_VERSION").replace("v", ""),
      AttributeError: 'NoneType' object has no attribute 'replace'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
And tried on 3.9.2 x64 on WSL
```
$ python3 -m pip install git+https://github.com/WhiteApfel/pyYaOTP.git
Collecting git+https://github.com/WhiteApfel/pyYaOTP.git
  Cloning https://github.com/WhiteApfel/pyYaOTP.git to /tmp/pip-req-build-orjuz985
  Running command git clone -q https://github.com/WhiteApfel/pyYaOTP.git /tmp/pip-req-build-orjuz985
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-orjuz985/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-orjuz985/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-abk96o52
         cwd: /tmp/pip-req-build-orjuz985/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-orjuz985/setup.py", line 19, in <module>
        version=environ.get("TAG_VERSION").replace("v", ""),
    AttributeError: 'NoneType' object has no attribute 'replace'
    ----------------------------------------
WARNING: Discarding git+https://github.com/WhiteApfel/pyYaOTP.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
It seems setup.py tries to use env variable `TAG_VERSION` and it doesn't exists so environ.get() returns None. I don't know why there should be such variable in env, probably it expected to be set by installation script.

Anyway, thanks for this implementation of yaotp. I will end up with installing it using pip.

**Comment by norohind** [comment]
Figured out it expected to be set by pypi publish workflow

**Comment by WhiteApfel** [comment]
Oh yep. You can set the tag along with installation start:
`TAG_VERSION=git python -m pip install git+https://github.com/WhiteApfel/pyYaOTP.git`

I don't really want to fix it. It is better to set the tag manually.

**Comment by norohind** [comment]
Thanks.
